# Generated by Django 5.0.4 on 2024-04-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Nombre Usuario')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('clave', models.CharField(max_length=30, verbose_name='Contrasenia')),
                ('edad', models.CharField(max_length=3, verbose_name='Edad')),
                ('pais', models.CharField(max_length=15, verbose_name='Pais')),
            ],
        ),
    ]
