# Generated by Django 5.1.7 on 2025-05-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_rename_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='clave',
            field=models.CharField(max_length=30, verbose_name='Clave'),
        ),
    ]
