# Generated by Django 5.1.7 on 2025-05-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_reserva_alter_user_clave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
